load("./Data/p_values_beta1_v1.Rdata")
#save(p_values_beta1, Z, file = "./Data/p_values_beta1_v1.Rdata")
save(p_values_beta1, Z, file = "./Data/p_values_beta1_v1_11.Rdata")
load("./Data/p_values_beta1_v1_11.Rdata")
load("./Data/p_values_smooth_gam.Rdata")
load("./Data/p_values_nlsLM.Rdata")
source("../imagematrix.R")
#hist(p_values_matrix)
#plot(imagematrix(p_values_matrix),significance_level = 0.05)
#plot(imagematrix(p_values_matrix ))
plot(imagematrix(p_values_smooth >0.001))
plot(imagematrix(p_values_beta1 >0.05))
#plot(imagematrix(equalize(difference_values)))
#plot(imagematrix(equalize(x)))